# Generated by Django 2.1.2 on 2019-01-04 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authboss', '0004_auto_20190105_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 12, 27, 457868))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheats', to='authboss.Profile')),
            ],
            options={
                'verbose_name': 'Шпаргалка',
                'verbose_name_plural': 'Шпаргалки',
            },
        ),
        migrations.CreateModel(
            name='Comment_to_discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 12, 27, 458865))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authboss.Profile')),
            ],
            options={
                'verbose_name': 'Комментарий к обсуждению',
                'verbose_name_plural': 'Комментарии к обсуждениям',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 12, 27, 458865))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='authboss.Profile')),
            ],
            options={
                'verbose_name': 'Обсуждение',
                'verbose_name_plural': 'Обсуждения',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 12, 27, 457868))),
                ('due_on', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='authboss.Profile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
