# Generated by Django 2.1.2 on 2018-12-27 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authboss', '0003_auto_20181218_2345'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_to_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 23, 30, 29, 294424))),
            ],
            options={
                'verbose_name': 'Комментарий к предмету',
                'verbose_name_plural': 'Комментарии к предметам',
            },
        ),
        migrations.CreateModel(
            name='Comment_to_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 12, 27, 23, 30, 29, 292435))),
            ],
            options={
                'verbose_name': 'Комментарий к преподавателю',
                'verbose_name_plural': 'Комментарии к преподавателям',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Оценка преподавателю', 'verbose_name_plural': 'Оценки преподавателей'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teachers.Faculty'),
        ),
        migrations.AddField(
            model_name='comment_to_teacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='comment_to_teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_teacher', to='authboss.Profile'),
        ),
        migrations.AddField(
            model_name='comment_to_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teachers.Subject'),
        ),
        migrations.AddField(
            model_name='comment_to_subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_subjects', to='authboss.Profile'),
        ),
    ]
