# Generated by Django 2.1.2 on 2019-01-04 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20181227_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_to_subject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 23, 30, 0, 237412)),
        ),
        migrations.AlterField(
            model_name='comment_to_teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 23, 30, 0, 235418)),
        ),
    ]
