# Generated by Django 2.1.2 on 2019-01-04 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20190104_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_to_subject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 23, 32, 28, 457004)),
        ),
        migrations.AlterField(
            model_name='comment_to_teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 23, 32, 28, 455037)),
        ),
    ]
