# Generated by Django 2.1.2 on 2019-01-04 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20190104_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_to_subject',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 12, 27, 455873)),
        ),
        migrations.AlterField(
            model_name='comment_to_teacher',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 0, 12, 27, 454876)),
        ),
    ]
