# Generated by Django 2.0.5 on 2018-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authboss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_name',
            field=models.BooleanField(default=False, verbose_name='Показать имя на сайте'),
        ),
    ]
