# Generated by Django 2.1.2 on 2018-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authboss', '0002_auto_20181217_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
